### ISSUE TITLE
Support juju actions for adding a new scrape target

### ISSUE THREAD

**Issue by balbirthomas** [canonical/prometheus-operator#26]
## Use case

A system administrator would like to add a new scrape target using a Juju action. 

## Open Questions
1. Why is this required/useful in additions to providing scrape targets using config and relation data ?
2. What parameters should the action have (for example IP address obviously) ?

**Comment by spads-spads** [comment]
1. This is useful as a stepping-stone for migration, or for polling third-party public endpoints that are not configured through juju, or even for out-of-controller juju environments where cross-model relations can't bridge the gap.
2. I would keep it simple, and use a URL and perhaps an optional comment or description field.  URLs are the structured data for service endpoints used on the Internet since the early 1990s, and have sufficient fields for host, endpoint, access credentials, path on remote service, and other unstructured data.  Python's `urlparse` only suffers from needing a second step to `partition` port from host in the `netspec` field.

**Comment by mmanciop** [comment]
About why is the action useful, besides what @spads-spads said already:
* Pulling into the monitoring system data about related managed services that are important to the Juju model

About the parameters, it may not be that simple. Scrape config has a bajilion things, because there are so many different systems out there. My two cents are:
1. From the [`scrape_config`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) data structure, pretty much anything that is not related to specific scrape targets, like scrape period and timeout, auth, tls configs, etc.
2. Depending on the available _metadata_ from the scraped endpoint, [relabeling](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) can be very useful. In this use-case, we can assume the scraped target is _not_ managed by Juju, so we do have to deal with exposing Juju topology (`controller_name`, `model_name`, `unit_name`) of the target system.

**Comment by dstathis** [comment]
I am a bit confused about what is being accomplished here. What is the difference between running an action to add a scrape target and just updating the scrape-config configuration value?

**Comment by mmanciop** [comment]
Well, actually Dylan has a great point, we have always discussed scrape configs as relationships, and there is no need for actions there. The gap is that relationships are not yet configurable as far as I know.

**Comment by balbirthomas** [comment]
> What is the difference between running an action to add a scrape target and just updating the scrape-config configuration value?

It seems clear from the use cases provided by @spads-spads that this feature request is meant to be convenience for the user in very specific circumstances. No doubt the primary means by which scrape configurations of the Prometheus operator will be set is through the relations it is part of. However as far as user convenience goes in order to add an (perhaps ad hoc) scrape target the steps (or rather single step) the user needs to do is

     juju run-action add-endpoint "http://blah.blah.blah ...

May I invite you to write the steps that a user will have to go through to create a YAML config file and then pass it's *contents* as a config option to Juju ? Could we reflect upon which is a more pleasant user experience ?

**Comment by dstathis** [comment]
If anything, I would think that the easiest would be something along the lines of

`juju config prometheus scrape-targets="1.2.3.4:1234,5.6.7.8:5678"`

**Comment by balbirthomas** [comment]
> If anything, I would think that the easiest would be something along the lines of

I do no think that will work because of the manner in which the config option has been implemented. It takes an arbitrary YAML config file. 

This is a moot point now, since having just spoken to @jlounder I gathered that the PR that merged config YAML option was approved accidentally. I will hence be creating another PR to have it removed.

**Comment by mmanciop** [comment]
After more discussions, we are coming up with a different design for defining scrape targets involving a proxy charm. When the spec if ready for review, we will post it on Discourse. @balbirthomas please close this issue :-)

**Comment by balbirthomas** [comment]
Closing as requested.
