### ISSUE TITLE
Support for targeting non charm targets

### ISSUE THREAD

**Issue by dstathis** [canonical/prometheus-operator#28]
I think that there should be some way of targeting systems which are not managed by Juju. This is important for a couple reasons.

1. Most production environments will inevitably require some systems that either can't have a charm or don't yet have a charm. Furthermore, it may be a large amount of work for some existing systems to be migrated to Juju. Without having the ability to target these systems, admins will need to deploy a separate Prometheus instance outside of Juju if they want to monitor these systems. At which point they likely won't deploy this charm at all. I would like to encourage adoption of our charms and Juju in general as much as possible.
2. When writing Prometheus support for a new charm, it is useful to have a quick and easy way to point monitoring at my system while I am still developing the data exporting functionality. Otherwise I have to write all of the code before I ever know if the data exporting works in the first place.

**Comment by balbirthomas** [comment]
1. While supporting "external targets" is not the primary goal of the Prometheus operator some provision for external targets could certainly be made. What [type](https://prometheus.io/docs/prometheus/latest/configuration/configuration/) of external scrape targets and configurations do you find to be common use cases ?
2. It is not clear why you need support for an "external target" (meaning not part of a charm) when you are trying to develop a **charm** that has a Prometheus metrics endpoint. If you have developed or developing a HTTP Prometheus metrics end point why can you not just use a command line HTTP client such as `wget` or `curl` to check the "data exporting functionality" ? It is not clear to me what you mean by "Otherwise I have to write all of the code before I ever know if the data exporting works in the first place" ? What is this "all the code" that you refer to ? Is it the code of a your charm's event handler that handles the relation with the prometheus charm ? This code is mostly one function call `add_endpoint()`. If on the other hand it is the code that implements the `/metrics` endpoint, why can you not test this independently of your charm (such as using `curl` as mentioned) or any other way that is standard practice among developers of Prometheus metric endpoints ?

**Comment by dstathis** [comment]
I discussed with @jlounder and it looks like this is best done through integrator charms which I had not considered.
